#!/bin/bash -l
#PBS -N "17_H2O"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb
cd /home/zw18965/work/HFREQ2014/aug-cc-pVTZ/wB97X-V
source /home/zw18965/.bashrc
#Setup scratch directory
tmp=${TMPDIR}
export MKL_THREADING_LAYER=""
conda activate p4env
cp 17_H2O.in ${tmp}
cd ${tmp}
psi4 -n 24 -i "17_H2O.in" -o  "17_H2O.out"
cp 17_H2O.* /home/zw18965/work/HFREQ2014/aug-cc-pVTZ/wB97X-V
cd /home/zw18965/work/HFREQ2014/aug-cc-pVTZ/wB97X-V
