#!/bin/bash -l
#PBS -N "19_HCl"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb
cd /home/zw18965/work/HFREQ2014/wB97X-V
source /home/zw18965/.bashrc
#Setup scratch directory
tmp=${TMPDIR}
export MKL_THREADING_LAYER=""
conda activate p4env
cp 19_HCl.in ${tmp}
cd ${tmp}
psi4 -n 24 -i "19_HCl.in" -o  "19_HCl.out"
cp 19_HCl.* /home/zw18965/work/HFREQ2014/wB97X-V
cd /home/zw18965/work/HFREQ2014/wB97X-V
