#!/bin/bash -l
#PBS -N "14_F2"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb

cd /home/zw18965/work/HFREQ2014/wB97M-V

source /home/zw18965/.bashrc

#Setup scratch directory
tmp=${TMPDIR}

export MKL_THREADING_LAYER=""
conda activate p4env

cp 14_F2.in ${tmp}
cd ${tmp}

psi4 -n 24 -i "14_F2.in" -o  "14_F2.out"
cp 14_F2.* /home/zw18965/work/HFREQ2014/wB97M-V

cd /home/zw18965/work/HFREQ2014/wB97M-V
