#!/bin/bash -l
#PBS -N "31_CH3OH"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb
cd /home/zw18965/work/HFREQ2014/aug-cc-pVQZ/wB97M-V
source /home/zw18965/.bashrc
#Setup scratch directory
tmp=${TMPDIR}
export MKL_THREADING_LAYER=""
conda activate p4env
cp 31_CH3OH.in ${tmp}
cd ${tmp}
psi4 -n 24 -i "31_CH3OH.in" -o  "31_CH3OH.out"
cp 31_CH3OH.* /home/zw18965/work/HFREQ2014/aug-cc-pVQZ/wB97M-V
cd /home/zw18965/work/HFREQ2014/aug-cc-pVQZ/wB97M-V
