#!/bin/bash -l
#PBS -N "01_BH3"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb
cd /home/zw18965/work/HFREQ2014/cc-pVQZ/wB97X-V
source /home/zw18965/.bashrc
#Setup scratch directory
tmp=${TMPDIR}
export MKL_THREADING_LAYER=""
conda activate p4env
cp 01_BH3.in ${tmp}
cd ${tmp}
psi4 -n 24 -i "01_BH3.in" -o  "01_BH3.out"
cp 01_BH3.* /home/zw18965/work/HFREQ2014/cc-pVQZ/wB97X-V
cd /home/zw18965/work/HFREQ2014/cc-pVQZ/wB97X-V
