#!/bin/bash -l
#PBS -N "15_H2CO"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb
cd /home/zw18965/work/HFREQ2014/aug-cc-pVTZ/wB97M-V
source /home/zw18965/.bashrc
#Setup scratch directory
tmp=${TMPDIR}
export MKL_THREADING_LAYER=""
conda activate p4env
cp 15_H2CO.in ${tmp}
cd ${tmp}
psi4 -n 24 -i "15_H2CO.in" -o  "15_H2CO.out"
cp 15_H2CO.* /home/zw18965/work/HFREQ2014/aug-cc-pVTZ/wB97M-V
cd /home/zw18965/work/HFREQ2014/aug-cc-pVTZ/wB97M-V
