#!/bin/bash -l
#PBS -N "09_ClF"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb
cd /home/zw18965/work/HFREQ2014/aug-cc-pVDZ/wB97M-V
source /home/zw18965/.bashrc
#Setup scratch directory
tmp=${TMPDIR}
export MKL_THREADING_LAYER=""
conda activate p4env
cp 09_ClF.in ${tmp}
cd ${tmp}
psi4 -n 24 -i "09_ClF.in" -o  "09_ClF.out"
cp 09_ClF.* /home/zw18965/work/HFREQ2014/aug-cc-pVDZ/wB97M-V
cd /home/zw18965/work/HFREQ2014/aug-cc-pVDZ/wB97M-V
