#!/bin/bash -l
#PBS -N "22_HNO"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb
cd /home/zw18965/work/HFREQ2014/aug-cc-pVDZ/wB97X-V
source /home/zw18965/.bashrc
#Setup scratch directory
tmp=${TMPDIR}
export MKL_THREADING_LAYER=""
conda activate p4env
cp 22_HNO.in ${tmp}
cd ${tmp}
psi4 -n 24 -i "22_HNO.in" -o  "22_HNO.out"
cp 22_HNO.* /home/zw18965/work/HFREQ2014/aug-cc-pVDZ/wB97X-V
cd /home/zw18965/work/HFREQ2014/aug-cc-pVDZ/wB97X-V
