#!/bin/bash -l
#PBS -N "03_C2H4"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb

cd /home/zw18965/work/HFREQ2014/DSD-BLYP-D3BJ

source /home/zw18965/.bashrc

#Setup scratch directory
tmp=${TMPDIR}

export MKL_THREADING_LAYER=""
conda activate p4env

cp 03_C2H4.in ${tmp}
cd ${tmp}

psi4 -n 24 -i "03_C2H4.in" -o  "03_C2H4.out"
cp 03_C2H4.* /home/zw18965/work/HFREQ2014/DSD-BLYP-D3BJ

cd /home/zw18965/work/HFREQ2014/DSD-BLYP-D3BJ
