#!/bin/bash -l
#PBS -N "06_CH4"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb

cd /home/zw18965/work/HFREQ2014/B2-PLYP-D3BJ

source /home/zw18965/.bashrc

#Setup scratch directory
tmp=${TMPDIR}

export MKL_THREADING_LAYER=""
conda activate p4env

cp 06_CH4.in ${tmp}
cd ${tmp}

psi4 -n 24 -i "06_CH4.in" -o  "06_CH4.out"
cp 06_CH4.* /home/zw18965/work/HFREQ2014/B2-PLYP-D3BJ

cd /home/zw18965/work/HFREQ2014/B2-PLYP-D3BJ
