#!/bin/bash -l
#PBS -N "18_H2S"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb

cd /home/zw18965/work/HFREQ2014/B2-PLYP-D3BJ

source /home/zw18965/.bashrc

#Setup scratch directory
tmp=${TMPDIR}

export MKL_THREADING_LAYER=""
conda activate p4env

cp 18_H2S.in ${tmp}
cd ${tmp}

psi4 -n 24 -i "18_H2S.in" -o  "18_H2S.out"
cp 18_H2S.* /home/zw18965/work/HFREQ2014/B2-PLYP-D3BJ

cd /home/zw18965/work/HFREQ2014/B2-PLYP-D3BJ
