#!/bin/bash -l
#PBS -N "21_HF"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb
cd /home/zw18965/work/HFREQ2014/cc-pVTZ/wB97M-V
source /home/zw18965/.bashrc
#Setup scratch directory
tmp=${TMPDIR}
export MKL_THREADING_LAYER=""
conda activate p4env
cp 21_HF.in ${tmp}
cd ${tmp}
psi4 -n 24 -i "21_HF.in" -o  "21_HF.out"
cp 21_HF.* /home/zw18965/work/HFREQ2014/cc-pVTZ/wB97M-V
cd /home/zw18965/work/HFREQ2014/cc-pVTZ/wB97M-V
