#!/bin/bash -l
#PBS -N "11_CO"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb
cd /home/zw18965/work/HFREQ2014/cc-pVDZ/wB97M-V
source /home/zw18965/.bashrc
#Setup scratch directory
tmp=${TMPDIR}
export MKL_THREADING_LAYER=""
conda activate p4env
cp 11_CO.in ${tmp}
cd ${tmp}
psi4 -n 24 -i "11_CO.in" -o  "11_CO.out"
cp 11_CO.* /home/zw18965/work/HFREQ2014/cc-pVDZ/wB97M-V
cd /home/zw18965/work/HFREQ2014/cc-pVDZ/wB97M-V
