#!/bin/bash -l
#PBS -N "23_HOCl"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb
cd /home/zw18965/work/HFREQ2014/cc-pVDZ/wB97M-V
source /home/zw18965/.bashrc
#Setup scratch directory
tmp=${TMPDIR}
export MKL_THREADING_LAYER=""
conda activate p4env
cp 23_HOCl.in ${tmp}
cd ${tmp}
psi4 -n 24 -i "23_HOCl.in" -o  "23_HOCl.out"
cp 23_HOCl.* /home/zw18965/work/HFREQ2014/cc-pVDZ/wB97M-V
cd /home/zw18965/work/HFREQ2014/cc-pVDZ/wB97M-V
